- name: Delete Route to expose Grafana
  kubernetes.core.k8s:
    state: absent
    definition:
      apiVersion: route.openshift.io/v1
      kind: Route
      metadata:
        name: grafana
        namespace: "{{ name_space }}"

- name: Delete Grafana instance using Operator
  kubernetes.core.k8s:
    state: absent
    definition:
      apiVersion: grafana.integreatly.org/v1beta1
      kind: Grafana
      metadata:
        name: grafana
        namespace: "{{ name_space }}"

