- name: Set default values for pod wait retries and delay (if not set)
  set_fact:
    pod_wait_retries: "{{ pod_wait_retries | default(20) }}"
    pod_wait_delay: "{{ pod_wait_delay | default(10) }}"

- name: Wait for all pods in namespace to be running
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: "{{ name_space }}"
  register: pods
  until: >-
    pods.resources | length > 0 and
    (pods.resources | selectattr('status.phase', 'equalto', 'Running') | list | length == pods.resources | length)
  retries: "{{ pod_wait_retries }}"
  delay: "{{ pod_wait_delay }}"
