- name: Delete ClusterRoleBinding for ServiceAccount
  kubernetes.core.k8s:
    state: absent
    definition:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: "{{ binding_name }}"

- name: Delete ServiceAccount token secret (if manually created)
  kubernetes.core.k8s:
    state: absent
    kind: Secret
    name: "{{ service_account_name }}-token"
    namespace: "{{ service_account_namespace }}"
  ignore_errors: true  # In case it was auto-created or already deleted

- name: Delete ServiceAccount
  kubernetes.core.k8s:
    state: absent
    definition:
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: "{{ service_account_name }}"
        namespace: "{{ service_account_namespace }}"